[package]
name = "web_page_main_canvas"
version = "0.1.0"
edition = "2024"
authors = ["N3cro0o"]

[lib]
name = "web_page_main_canvas_lib"
path = "src/lib.rs"

[[bin]]
name = "web_page_main_canvas_bin"
path = "src/main.rs"

[dependencies]
console_error_panic_hook = {workspace = true}
iced = {workspace = true}
wasm-bindgen = {workspace = true}
wasmtimer = {workspace = true}
web-sys = {workspace = true}
