name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen
        run: |
          cargo install wasm-bindgen-cli --version "0.2.128"
          wasm-bindgen --version

      - name: Build and prepare wasm
        working-directory: ./wasm
        run: |
          cargo b --release --target wasm32-unknown-unknown -p web_page_main_canvas
          mkdir output
          mkdir output/main
          wasm-bindgen --target web --out-dir output\main\  .\target\wasm32-unknown-unknown\release\web_page_main_canvas_bin.wasm


  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
